-- ================================================================
-- Script Name   : schema.sql
-- Project       : Student Performance Tracker
-- Author        : J. Anitha
-- Purpose       : Defines database schema (tables and relationships)
-- ================================================================
CREATE TABLE student (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50),
    class VARCHAR2(10),
    email VARCHAR2(100)
);

CREATE TABLE subject (
    subject_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_name VARCHAR2(50),
    max_marks NUMBER(3)
);

CREATE TABLE marks (
    student_id NUMBER REFERENCES student(student_id),
    subject_id NUMBER REFERENCES subject(subject_id),
    marks_obtained NUMBER(3),
    PRIMARY KEY(student_id, subject_id)
);

CREATE TABLE result (
    student_id NUMBER PRIMARY KEY REFERENCES student(student_id),
    total_marks NUMBER(5),
    percentage NUMBER(5,2),
    grade CHAR(1)
);
